const prefix = "ces/containers/";

const EVENT_PRESSED = prefix + "EVENT_PRESSED";
const EVENT_LOADING = prefix + "EVENT_LOADING";
const EVENT_CLOSED = prefix + "EVENT_CLOSED";
const ATTEND_PRESSED = prefix + "ATTEND_PRESSED";
const EVENTS_UPDATED = prefix + "EVENTS_UPDATED";
const VERIFIED_ATTENDING = prefix + "VERIFIED_ATTENDING";
const ATTEND_FAILED = prefix + "ATTEND_FAILED";
const ATTEND_CANCEL = prefix + "ATTEND_CANCEL";
const FILTER_CHANGED = prefix + "FILTER_CHANGED";


export {

    EVENT_PRESSED,
    ATTEND_PRESSED,
    ATTEND_FAILED,
    EVENTS_UPDATED,
    EVENT_LOADING,
    EVENT_CLOSED,
    ATTEND_CANCEL,
    VERIFIED_ATTENDING,
    FILTER_CHANGED,
    
};

