const PREFIX = "CES/UsersPage/";
const ADD_FILTER = PREFIX + "ADD_FILTER";
const REMOVE_FILTER = PREFIX + "REMOVE_FILTER";
const LOAD_USERS = PREFIX + "LOAD_USERS";
const LOADED_USERS = PREFIX + "LOADED_USERS";

export {

    ADD_FILTER,
    REMOVE_FILTER,
    LOAD_USERS,
    LOADED_USERS,
}
